### ISSUE TITLE
cl script dropping into REPL upon unhandled error on ABCL

### ISSUE THREAD

**Issue by luismbo** [KeenS/CIM#41] opened 2014-12-18 00:06 UTC
This quickload command is signalling an error which is triggering the interactive debugger.

    $ cl -e '(ql:quickload :trivial-features-tests)'
    Error loading /home/travis/build/trivial-features/trivial-features/trivial-features-tests.asd at line 47 (offset 2007)
    #<THREAD "interpreter" {55D020CF}>: Debugger invoked on condition of type LOAD-SYSTEM-DEFINITION-ERROR
      Error while trying to load definition for system trivial-features-tests from pathname /home/travis/build/trivial-features/trivial-features/trivial-features-tests.asd: Component ASDF/USER::CFFI-GROVEL not found, required by NIL
    Restarts:
      0: RETRY                         Retry loading CFFI-GROVEL.
      1: RETRY                         Retry ASDF operation.
      2: CLEAR-CONFIGURATION-AND-RETRY Retry ASDF operation after resetting the configuration.
      3: ABORT                         Give up on "trivial-features-tests"
    [1] ASDF/USER(1):

**Comment by KeenS** [comment] 2015-01-01 14:47
This bug didn't occur on my environment. could you give me more precise reproduction code?

**Comment by fukamachi** [comment] 2015-01-11 16:46
You can reproduce it by `cim use abcl; cl -e '(error "hi")'`.
This is inconvenient for testing on Travis CI because it get stuck until the timeout.

**Comment by KeenS** [comment] 2015-01-12 11:59
@fukamachi @luismbo Verified. Will be fixed in a few days.

**Closed** 2015-04-20 12:39 UTC
